### Explication

In [106]:
import pandas as pd
import numpy as np

In [107]:
df_codepostal = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")

In [108]:
codes = {'M5G':0,'M2H':1,'M4B':2,'M1J':3, 'M4G':4, 'M4M':5, 'M1R':6, 'M9V':7, 'M9L':8, 'M5V':9, 'M1B':10, 'M5A':11}

In [109]:
df_html=pd.DataFrame(df_codepostal[0]).dropna()
df_html

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Regent Park / Harbourfront
5,M6A,North York,Lawrence Manor / Lawrence Heights
6,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
...,...,...,...
160,M8X,Etobicoke,The Kingsway / Montgomery Road / Old Mill North
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,Business reply mail Processing CentrE
169,M8Y,Etobicoke,Old Mill South / King's Mill Park / Sunnylea /...
178,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...

In [110]:
tab1={}
for i in range(103):
    if df_html.iloc[i]["Postal code"] in codes:
        idx=codes[df_html.iloc[i]["Postal code"]]
        tab1[idx] = df_html.iloc[i]
        
df_tab1=pd.DataFrame(tab1).transpose()
df_tab1=df_tab1.rename(columns={"Postal code": "PostalCode"}).sort_index()
df_tab1= df_tab1.replace(to_replace="\/", value=",", regex=True)
df_tab1

,PostalCode,Borough,Neighborhood
0,M5G,Downtown Toronto,Central Bay Street
1,M2H,North York,Hillcrest Village
2,M4B,East York,"Parkview Hill , Woodbine Gardens"
3,M1J,Scarborough,Scarborough Village
4,M4G,East York,Leaside
5,M4M,East Toronto,Studio District
6,M1R,Scarborough,"Wexford , Maryvale"
7,M9V,Etobicoke,"South Steeles , Silverstone , Humbergate , Jam..."
8,M9L,North York,Humber Summit
9,M5V,Downtown Toronto,"CN Tower , King and Spadina , Railway Lands , ..."
10,M1B,Scarborough,"Malvern , Rouge"
11,M5A,Downtown Toronto,"Regent Park , Harbourfront"

In [111]:
df_geo = pd.read_csv("http://cocl.us/Geospatial_data").dropna()
df_geo

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [112]:
tab2={}
for i in range(103):
    if df_geo.iloc[i]["Postal Code"] in codes:
        idx=codes[df_geo.iloc[i]["Postal Code"]]
        tab2[idx] = df_geo.iloc[i]
        
df_tab2=pd.DataFrame(tab2).transpose().sort_index()
df_tab2=df_tab2.rename(columns={"Postal Code": "PostalCode"})
df_tab2

   PostalCode Latitude Longitude
0         M5G   43.658  -79.3874
1         M2H  43.8038  -79.3635
2         M4B  43.7064  -79.3099
3         M1J  43.7447  -79.2395
4         M4G  43.7091  -79.3635
5         M4M  43.6595  -79.3409
6         M1R  43.7501  -79.2958
7         M9V  43.7394  -79.5884
8         M9L  43.7563   -79.566
9         M5V  43.6289  -79.3944
10        M1B  43.8067  -79.1944
11        M5A  43.6543  -79.3606

In [113]:
df=pd.merge(df_tab1, df_tab2)
df

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M5G,Downtown Toronto,Central Bay Street,43.658,-79.3874
1,M2H,North York,Hillcrest Village,43.8038,-79.3635
2,M4B,East York,"Parkview Hill , Woodbine Gardens",43.7064,-79.3099
3,M1J,Scarborough,Scarborough Village,43.7447,-79.2395
4,M4G,East York,Leaside,43.7091,-79.3635
5,M4M,East Toronto,Studio District,43.6595,-79.3409
6,M1R,Scarborough,"Wexford , Maryvale",43.7501,-79.2958
7,M9V,Etobicoke,"South Steeles , Silverstone , Humbergate , Jam...",43.7394,-79.5884
8,M9L,North York,Humber Summit,43.7563,-79.566
9,M5V,Downtown Toronto,"CN Tower , King and Spadina , Railway Lands , ...",43.6289,-79.3944
10,M1B,Scarborough,"Malvern , Rouge",43.8067,-79.1944
11,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.6543,-79.3606